spring:
  application:
    name: maxbot-back

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}

    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: ${PINECONE_INDEX_NAME}
        project-id: ${PINECONE_PROJECT_ID}



logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
