spring:
  application:
    name: maxbot-back

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}

    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: ${PINECONE_INDEX_NAME}
        project-id: ${PINECONE_PROJECT_ID}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB


logging:
  level:
    org:
      springframework:
        ai: DEBUG
        web: INFO