spring:
  application:
    name: maxbot-back

  ## OpenAI LLM configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0

    ## Pinecone vector store configuration
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: maxbot-vector
        project-id: 479f03d6-0255-4c9e-a91a-3d71166a0818

  ## File upload configuration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

## Logging configuration
logging:
  level:
    org:
      springframework:
        ai: DEBUG
        web: INFO

## LLM Prompt configuration
PROMPT_SYSTEM_TEMPLATE: |
  Tu es un assistant utile nomé MaxBot, tu vouvoie toujours, et ton rôle est de répondre seulement aux questions
  concernant Maxime DROUAULT.