spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        options:
          model: ${OLLAMA_MODEL}
          temperature: ${OLLAMA_TEMPERATURE}

#    openai:
#      api-key: ${GROQ_API_KEY}
#      base-url: ${GROQ_BASE_URL}
#      chat:
#        options:
#          model: ${GROQ_MODEL}
#          temperature: ${GROQ_TEMPERATURE}

  application:
    name: maxbot-back